name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the api_gateway
      run: docker build api_gateway --file api_gateway/Dockerfile --tag api_gateway:lastest
