name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the api_gateway
      run: docker build api_gateway --file api_gateway/Dockerfile --tag api_gateway:lastest
    - name: Build the users
      run: docker build users --file users/Dockerfile --tag users:lastest
    - name: Build the books
      run: docker build books --file books/Dockerfile --tag books:lastest
    - name: Build the rental
      run: docker build rental --file rental/Dockerfile --tag rental:lastest

    
